const GET_ARTICLE_DATA = 'GET_ARTICLE_DATA'
const CHANGE_GREETING = 'CHANGE_GREETING'
const PREPARE_GREETING = 'PREPARE_GREETING'
const AUTHENTICATE = 'AUTHENTICATE'


export { GET_ARTICLE_DATA, CHANGE_GREETING, PREPARE_GREETING, AUTHENTICATE }